# Starter pipeline



# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  name: Default  # Replace with the actual name of your agent pool if different

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: 'mvn clean'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        mvn clean
        mvn test
        mvn compile
        mvn package



  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: 'C:\IT/$(Build.BuildId).zip'
      replaceExistingArchive: true

  # - task: GenerateVersionStamp@2
  #   inputs:
  #     targetPath: '/home/omer/myagent/Versions/VersionStamp.txt'
  #     format: '$(MajorVersion).$(MinorVersion).$(BuildNumber)